import json
import os
from datetime import datetime

from rag_retriever import retrieve_knowledge

try:
    from mistralai import Mistral

except ImportError as e:
    raise ImportError(
        "Could not import Mistral SDK. Ensure mistralai>=1.0.0 is installed."
    ) from e


SECURITY_CONTEXT_FILE = "output/combined_security_context.json"
REMEDIATION_FILE = "output/remediation_plan.json"
REPORT_FILE = "output/quantum_security_report.md"


# =========================
# LOADERS
# =========================

def load_json(path):

    with open(path, "r") as file:
        return json.load(file)



def load_security_context():

    return load_json(
        SECURITY_CONTEXT_FILE
    )



def load_remediation_plan():

    return load_json(
        REMEDIATION_FILE
    )



# =========================
# MISTRAL
# =========================

def ask_mistral(prompt):

    api_key = os.getenv(
        "MISTRAL_API_KEY"
    )

    if not api_key:

        raise ValueError(
            "MISTRAL_API_KEY is missing"
        )


    client = Mistral(
        api_key=api_key
    )


    response = client.chat.complete(

        model="mistral-small-latest",

        messages=[

            {
                "role": "system",

                "content": """

You are a Senior Application Security Engineer
specializing in Post Quantum Cryptography.

Generate an enterprise security assessment report.

STRICT SECURITY RULES:

Evidence Grounding:

Use ONLY:

- CBOM findings
- SonarQube findings
- Remediation plan
- Retrieved NIST knowledge


Hallucination Prevention:

Never invent:

- vulnerabilities
- algorithms
- files
- line numbers
- rules
- NIST references
- migration standards


NIST Rules:

- Use only retrieved NIST evidence.
- Include the source filename.
- Do not create external references.
- If retrieval is empty write:

"No NIST evidence available."


Score Rules:

- Quantum Readiness Score is generated by the security engine.
- Copy exactly.
- Never recalculate.


Evidence Rules:

If evidence does not exist write:

"No evidence available."


Sonar Rules:

Only use exact:

- file name
- line number
- severity
- rule
- message

from Sonar evidence.


Generate professional enterprise security documentation.

"""

            },

            {
                "role": "user",
                "content": prompt
            }

        ]

    )


    return response.choices[0].message.content



# =========================
# NORMALIZATION
# =========================

def normalize_algorithm(name):

    if not name:
        return ""

    return (
        name.upper()
        .replace("-", "")
        .replace("_", "")
        .replace(" ", "")
    )



def normalize_risk(value):

    if not value:

        return "LOW"

    return value.upper()



# =========================
# READINESS SCORE
# =========================

def calculate_readiness_score(findings):


    if not findings:

        return 100


    score = 100

    analyzed = set()


    for finding in findings:


        algorithm = normalize_algorithm(
            finding.get("asset", "")
        )


        if algorithm in analyzed:

            continue


        analyzed.add(
            algorithm
        )


        if (
            "RSAOAEP" in algorithm
            or algorithm == "RSA"
        ):

            score -= 20


        elif "MD5" in algorithm:

            score -= 15


        elif "SHA1" in algorithm:

            score -= 10


        elif "AES128" in algorithm:

            score -= 5


        elif (
            "MLKEM" in algorithm
            or "MLDSA" in algorithm
        ):

            score += 10



    return max(
        min(score,100),
        0
    )



# =========================
# MIGRATION WAVES
# =========================

def generate_migration_waves(findings):


    waves = {

        "Wave 1 - Immediate": [],

        "Wave 2 - High Priority": [],

        "Wave 3 - Optimization": []

    }



    for finding in findings:


        asset = finding.get(
            "asset"
        )


        risk = normalize_risk(
            finding.get("risk")
        )


        if risk in [
            "CRITICAL",
            "HIGH"
        ]:

            waves[
                "Wave 1 - Immediate"
            ].append(asset)


        elif risk == "MEDIUM":

            waves[
                "Wave 2 - High Priority"
            ].append(asset)


        else:

            waves[
                "Wave 3 - Optimization"
            ].append(asset)



    return waves



# =========================
# NIST QUERY GENERATOR
# =========================

def get_nist_query(asset, category):


    algorithm = normalize_algorithm(
        asset
    )


    nist_queries = {


        "RSAOAEP":

        """
NIST FIPS 203 ML-KEM migration guidance.

RSA-OAEP replacement using
post quantum key encapsulation mechanism.

Hybrid cryptography transition guidance.
""",


        "RSA":

        """
NIST post quantum cryptography migration.

RSA replacement using FIPS 203 ML-KEM
and FIPS 204 ML-DSA.

Migration guidance.
""",


        "SHA1":

        """
NIST SP 800-131A SHA-1 transition guidance.

SHA-1 deprecation,
SHA-256 and SHA-3 migration.
""",


        "MD5":

        """
NIST cryptographic hash transition guidance.

MD5 deprecated replacement using
secure hash algorithms.
""",


        "AES128":

        """
NIST guidance on AES-128,
Grover algorithm,
and AES-256 quantum security.
""",


        "AES256":

        """
NIST guidance on AES-256
quantum resistant symmetric cryptography.
"""

    }



    # longest match first
    for key, query in sorted(
        nist_queries.items(),
        key=lambda x: len(x[0]),
        reverse=True
    ):


        if key in algorithm:

            return query



    return f"""

NIST post quantum cryptography migration guidance.

Algorithm:

{asset}


Category:

{category}

Find applicable:
- FIPS standards
- migration guidance
- replacement algorithms

"""
# =========================
# BUILD PROMPT
# =========================

def build_prompt(context, remediation_plan):


    pqc_findings = context.get(
        "pqc_findings",
        []
    )


    sonar_findings = context.get(
        "sonarqube_findings",
        []
    )


    assessment_date = datetime.utcnow().strftime(
        "%Y-%m-%d"
    )


    readiness_score = calculate_readiness_score(
        pqc_findings
    )


    migration_waves = generate_migration_waves(
        pqc_findings
    )


    pqc_context = []

    nist_context = []



    print("\n========== RAG VALIDATION ==========")



    for finding in pqc_findings:


        asset = finding.get(
            "asset",
            ""
        )


        category = finding.get(
            "category",
            ""
        )


        #
        # Generate specific NIST query
        #
        query = get_nist_query(
            asset,
            category
        )


        print("\nQUERY:")
        print(asset)

        print(query)



        #
        # Retrieve NIST evidence
        #
        retrieved = retrieve_knowledge(
            query,
            k=5
        )



        if not retrieved:

            retrieved = [
                {
                    "content":
                    "No NIST evidence available.",
                    "source":
                    None
                }
            ]



        print("\nRESULTS:")


        for item in retrieved:

            print(
                "\nSOURCE:",
                item.get("source")
            )

            print(
                "CONTENT:",
                item.get("content")[:300]
            )



        print(
            "\n--------------------------------"
        )



        nist_context.append(

            {

                "algorithm":
                asset,


                "category":
                category,


                "query":
                query,


                "retrieved_evidence":
                retrieved

            }

        )



        pqc_context.append(

            {

                "finding_id":
                finding.get(
                    "finding_id"
                ),


                "asset":
                asset,


                "risk":
                finding.get(
                    "risk"
                ),


                "category":
                category,


                "priority":
                finding.get(
                    "priority"
                ),


                "reason":
                finding.get(
                    "reason"
                ),


                "migration":
                finding.get(
                    "migration"
                ),


                "recommended_algorithm":
                finding.get(
                    "recommended_algorithm"
                ),


                "transition_strategy":
                finding.get(
                    "transition_strategy"
                ),


                "evidence":
                finding.get(
                    "evidence",
                    []
                )

            }

        )



    print("\n========== END RAG VALIDATION ==========\n")



    prompt = f"""

# Quantum Security Assessment Report


Assessment Date:

{assessment_date}



Prepared By:

Senior Application Security & Post Quantum Cryptography Engineer



Scope:

Cryptographic assets,
source code vulnerabilities,
and migration readiness.



IMPORTANT SECURITY ENGINE OUTPUT:


Quantum Readiness Score:

{readiness_score}%



IMPORTANT:

Copy this score exactly.

Do not modify.

Do not recalculate.



Generate:


# Executive Summary


Include:

- Current quantum readiness
- Major cryptographic risks
- Application security risks
- Migration urgency



# Quantum Readiness Score


Score:

{readiness_score}%



Explain only using provided findings.



# PQC Findings


For every finding include:


Asset:

Finding ID:

Risk:

Category:

Priority:

Why it matters:


Evidence:

Use only CBOM evidence.



# Migration Assessment


Current State:

Target State:

Recommended Algorithm:

Transition Strategy:

Migration Wave:

Estimated Effort:

Owner:

Confidence:



# SonarQube Code Security Findings


Use ONLY provided SonarQube evidence.


Include:


File:

Line:

Severity:

Type:

Rule:

Message:

Security Impact:

Recommended Fix:



# NIST Guidance


STRICT RULES:


- Use ONLY retrieved NIST evidence.
- Mention source filename.
- Do not create FIPS numbers.
- Do not create SP references.
- Do not use outside knowledge.


If evidence is missing:

"No NIST evidence available."



# Migration Roadmap


{json.dumps(
    migration_waves,
    indent=2
)}



# Limitations


Include:

- Assessment scope
- Evidence limitations
- Unknown cryptographic assets
- Implementation dependencies



============================

PQC Evidence:

{json.dumps(
    pqc_context,
    indent=2
)}



============================

Retrieved NIST Evidence:

{json.dumps(
    nist_context,
    indent=2
)}



============================

SonarQube Evidence:

{json.dumps(
    sonar_findings,
    indent=2
)}



============================

Remediation Plan:

{json.dumps(
    remediation_plan,
    indent=2
)}



"""


    return prompt




# =========================
# MAIN
# =========================

if __name__ == "__main__":


    context = load_security_context()


    remediation_plan = load_remediation_plan()



    pqc_findings = context.get(
        "pqc_findings",
        []
    )


    sonar_findings = context.get(
        "sonarqube_findings",
        []
    )



    print(
        "\nAnalyzing:"
    )


    print(
        "PQC findings:",
        len(pqc_findings)
    )


    print(
        "Sonar findings:",
        len(sonar_findings)
    )



    score = calculate_readiness_score(
        pqc_findings
    )


    print(
        "\nQuantum Readiness Score:",
        score,
        "%"
    )



    prompt = build_prompt(
        context,
        remediation_plan
    )



    print(
        "\nGenerating report..."
    )



    report = ask_mistral(
        prompt
    )



    os.makedirs(
        "output",
        exist_ok=True
    )



    with open(
        REPORT_FILE,
        "w"
    ) as file:

        file.write(
            report
        )



    print(
        "\nReport saved:"
    )


    print(
        REPORT_FILE
    )